name: Setup Syft
description: Install Syft for SBOM generation

runs:
  using: composite
  steps:
    - name: Install Syft
      uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
