apiVersion: v1
kind: Pod
metadata:
  name: test-init-unsigned
  labels:
    test: mixed-signed-unsigned
spec:
  initContainers:
    - name: unsigned-init
      image: europe-west1-docker.pkg.dev/stoked-citizen-455416-g4/supply-chain-security/supply-chain-demo:unsigned-test
      command: ["sh", "-c", "echo init done"]
  containers:
    - name: signed-main
      image: europe-west1-docker.pkg.dev/stoked-citizen-455416-g4/supply-chain-security/supply-chain-demo@sha256:cc52d2fbd3678cf16b0df5ff21a78a6d3c68d32778a1b5589182310e9a56e37a
      command: ["sh", "-c", "sleep 3600"]
  restartPolicy: Never