replicaCount: 2

image:
  repository: europe-west1-docker.pkg.dev/stoked-citizen-455416-g4/supply-chain-security/supply-chain-demo
  digest: sha256:116776c8ca1518c1ec08245ff241cf41b9f379854d747312da59eefe427698a9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10