apiVersion: v1
kind: Pod
metadata:
  name: test-mixed-containers
  namespace: default
spec:
  containers:
    - name: signed-container
      image: 5936/supply-chain-demo:latest
    - name: unsigned-container
      image: 5936/supply-chain-demo:unsigned-test