apiVersion: v1
kind: Pod
metadata:
  name: test-init-unsigned
  namespace: default
spec:
  initContainers:
    - name: unsigned-init
      image: 5936/supply-chain-demo:unsigned-test
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
  containers:
    - name: signed-main
      image: 5936/supply-chain-demo@sha256:1a4ebba1cec3bc49af1ff7260fa7566c4b09fe5ae834d518619ef0023ae91102
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true