apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-cosign
spec:
  name: cosign
  artifactTypes: application/vnd.dev.cosign.artifact.sig.v1+json
  parameters:
    trustPolicies:
      - name: default
        scopes:
          - "europe-west1-docker.pkg.dev/stoked-citizen-455416-g4/supply-chain-security/*"
        keyless:
          certificateIdentity: "https://github.com/musaumakau/supply-chain-security/.github/workflows/sign-attest.yml@refs/heads/main"
          certificateOIDCIssuer: "https://token.actions.githubusercontent.com"